apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GKEClusterClass
metadata:
  name: gkecluster-standard-dev
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  machineType: n1-standard-1
  numNodes: 1
  zone: us-west2
  providerRef:
    name: example
  reclaimPolicy: Delete

